## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [ ]:
import tensorflow as tf
x = tf.Variable(0.)
with tf.GradientTape() as tape:
  y = tf.square(x) + 3*x +1
gradient = tape.gradient(y, x)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [ ]:
X = tf.Variable(tf.random.uniform((2,2)))
with tf.GradientTape() as tape:
  y = tf.matmul(X,tf.matmul(X,X)) + 3*X +5
gradient = tape.gradient(y, X)
gradient 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7.1792703, 4.8835297],
       [8.79107  , 6.0260077]], dtype=float32)>

### Q3 Differentiate $z = X^3 y^2 + 3X + 2Xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [ ]:
X = tf.Variable(tf.random.uniform((2,2)))
y = tf.Variable(0.)
with tf.GradientTape() as tape:
  z = tf.matmul(X,tf.matmul(X,X)) * tf.square(y) + 3*X + 2*X*y +1
gradient = tape.gradient(z, [X,y])
gradient

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[3., 3.],
        [3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.9636848>]